### ISSUE TITLE
Schema object cannot have additionalProperty LB4 App

### ISSUE THREAD

**Issue by marioestradarosa** [strongloop/oasgraph#36]
## Steps to reproduce

- Create a loopback 4 app
- Create a datasource to Mysql 
- Create the student model, repository an controller

Make sure it works thru browser. Then follow the oasgraph quick start guide as follows:
- Clone oasgraph
- cd to oasgraph
- run npm link 
-  copy the openapi.json file from loopback 4 app running to my current oasgrahp directory (see attached, I placed .txt at the end to allow github attachment)
     using wget http://localhost:3000/openapi.json 
-  run oasgraph openapi.json

### The following error was received:

```sh
{ AssertionError: Schema object cannot have additionalProperty: patternProperties
    at Assertion.fail (/Users/marioestradarosa/test/oasgraph/node_modules/should/as-function.js:275:17)
    at Assertion.value (/Users/marioestradarosa/test/oasgraph/node_modules/should/as-function.js:356:19)
    at checkSubSchema (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:131:16)
    at walkSchema (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/node_modules/oas-schema-walker/index.js:53:5)
    at Object.walkSchema (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/node_modules/oas-schema-walker/index.js:82:13)
    at checkSchema (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:332:8)
    at checkContent (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:380:13)
    at checkResponse (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:569:9)
    at checkPathItem (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:782:21)
    at Object.validateSync (/Users/marioestradarosa/test/oasgraph/node_modules/oas-validator/index.js:1160:13)
  operator: 'to be above -1',
  message: 'Schema object cannot have additionalProperty: patternProperties',
  actual: -1,
  stackStartFunction: [Function: assert],
  negate: false,
  assertion: 
   Assertion {
     obj: -1,
     anyOne: false,
     negate: false,
     params: 
      { operator: 'to be above -1',
        message: 'Schema object cannot have additionalProperty: patternProperties',
        actual: -1,
        stackStartFunction: [Function: assert],
        negate: false,
        assertion: [Circular] },
     onlyThis: undefined,
     light: false } }

```

Attached openapi.json file.
[openapi.json.txt](https://github.com/strongloop/oasgraph/files/2430291/openapi.json.txt)

**Comment by raymondfeng** [comment]
It’s related to https://github.com/strongloop/loopback-next/pull/1755. I did not realize that OAS does not allow patternProperties. We need to use a different way to describe headers.

**Comment by marioestradarosa** [comment]
Thanks  @raymondfeng , I just started playing around with this library.

**Comment by marioestradarosa** [comment]
> We need to use a different way to describe headers.

Are these headers only for ping controller?,  I just removed the ping controller spec from openapi.json file and it seems to be running now, albeit still with some complains like (**Delete** _operation having InvalidSchemaType_).

**Comment by raymondfeng** [comment]
Just for ping controller

**Comment by raymondfeng** [comment]
Based on https://swagger.io/docs/specification/data-models/data-types/#object, we can probably use free form object.

**Comment by raymondfeng** [comment]
Mario, feel free to submit a patch. Thanks!
