### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Could not resolve reference ...

### ISSUE THREAD

**Issue by simax** [strongloop/oasgraph#91]
I'm trying to use our own [swagger.json file](https://api.ekm.net/swagger/v1/swagger.json) with `OASGraph` by using the example code from the library tutorial with the contents of the aforementioned swagger file. When I do so I get the following error:

``` 
(node:11544) UnhandledPromiseRejectionWarning: Error: Could not resolve reference #/definitions/TempestResponse[Category]
    at throwError (C:\Development\OASGraph\myapp\node_modules\swagger2openapi\index.js:32:15)
    at throwOrWarn (C:\Development\OASGraph\myapp\node_modules\swagger2openapi\index.js:47:9)
    at fixupRefs (C:\Development\OASGraph\myapp\node_modules\swagger2openapi\index.js:203:17)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:37:9)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
    at recurse (C:\Development\OASGraph\myapp\node_modules\reftools\lib\recurse.js:51:13)
(node:11544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by simax** [comment]
Please ignore. Entirely my fault. I was using an incomplete swagger.json file.

**Comment by ErikWittern** [comment]
Phew...
